version: '3.8'

services:
  postgres-db:
    container_name: pokedex_postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=test
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  go-app:
    container_name: go-app
    build: .
    ports:
      - 8080:8080
    depends_on:
      postgres-db:
        condition: service_healthy

