package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"fmt"

	"github.com/prae014/pokemon/graph/model"
)

//TODO: look at ID and stuff
//TODO: haven't tested update func and whatever came after that

func TypeInputMap(pkmn_type_input []*model.PokemonTypeInput) (pkmn_type []*model.PokemonType) {
	var pt []*model.PokemonType

	for _, type_input := range pkmn_type_input {
		t := model.PokemonType{
			Name: type_input.Name,
		}
		pt = append(pt, &t)
	}
	return pt
}

func AbilityInputMap(pkmn_ability_input []*model.PokemonAbilityInput) (pkmn_type []*model.PokemonAbility) {
	var pa []*model.PokemonAbility

	for _, ability_input := range pkmn_ability_input {
		a := model.PokemonAbility{
			Name: ability_input.Name,
		}
		pa = append(pa, &a)
	}
	return pa
}

// CreatePokemon is the resolver for the createPokemon field.
func (r *mutationResolver) CreatePokemon(ctx context.Context, input model.PokemonInput) (*model.Pokemon, error) {
	//r.DB.Select()
	//fmt.Println(r.DB)

	new_pkmn := model.Pokemon{
		Name:        input.Name,
		Description: input.Description,
		Category:    input.Category,
		Type:        TypeInputMap(input.Type),
		Abilities:   AbilityInputMap(input.Abilities),
	}

	//add to database
	err := r.DB.Create(&new_pkmn).Error
	if err != nil {
		return nil, err
	}
	fmt.Println("hereeeee")
	fmt.Println(new_pkmn.Name)

	return &new_pkmn, nil
	//panic(fmt.Errorf("not implemented: CreatePokemon - createPokemon"))
}

// UpdatePokemon is the resolver for the updatePokemon field.
func (r *mutationResolver) UpdatePokemon(ctx context.Context, id int, input model.PokemonInput) (*model.Pokemon, error) {
	//first check if ID exists or not
	var poke model.Pokemon
	p := r.DB.First(&poke, id)
	if p.Error != nil {
		return nil, p.Error
	}

	updated_poke := model.Pokemon{
		ID:          id,
		Name:        input.Name,
		Description: input.Description,
		Category:    input.Category,
		Type:        TypeInputMap(input.Type),
		Abilities:   AbilityInputMap(input.Abilities),
	}
	r.DB.Save(&updated_poke)
	return &updated_poke, nil
	//panic(fmt.Errorf("not implemented: UpdatePokemon - updatePokemon"))
}

// DeletePokemon is the resolver for the deletePokemon field.
func (r *mutationResolver) DeletePokemon(ctx context.Context, id int) (bool, error) {
	p := r.DB.Delete(&model.Pokemon{}, id)
	if p.RowsAffected < 1 {
		fmt.Printf("numbers of row affected: %v\n", p.RowsAffected)
		fmt.Println("The provided id doesn't exist")
		return false, nil //FIXME: nil here is a placeholder
	}
	return true, nil
	//panic(fmt.Errorf("not implemented: DeletePokemon - deletePokemon"))
}

// Pokemons is the resolver for the pokemons field.
func (r *queryResolver) Pokemons(ctx context.Context) ([]*model.Pokemon, error) {
	var all_poke []*model.Pokemon
	r.DB.Preload("Type").Preload("Abilities").Find(&all_poke)

	return all_poke, nil
	//panic(fmt.Errorf("not implemented: Pokemons - pokemons"))
}

// PokemonID is the resolver for the pokemonID field.
func (r *queryResolver) PokemonID(ctx context.Context, id int) (*model.Pokemon, error) {
	var poke model.Pokemon
	err := r.DB.First(&poke, id).Preload("Type").Preload("Abilities").Error

	if err != nil {
		return nil, err
	}
	return &poke, nil

	//panic(fmt.Errorf("not implemented: PokemonID - pokemonID"))
}

// PokemonName is the resolver for the pokemonName field.
func (r *queryResolver) PokemonName(ctx context.Context, name string) (*model.Pokemon, error) {
	var poke model.Pokemon
	err := r.DB.Where("name = ?", name).Preload("Type").Preload("Abilities").Find(&poke).Error

	if err != nil {
		return nil, err
	}
	return &poke, nil
	//panic(fmt.Errorf("not implemented: PokemonName - pokemonName"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
