// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Pokemon struct {
	ID          int               `json:"id"`
	Name        string            `json:"name"`
	Description string            `json:"description"`
	Category    string            `json:"category"`
	Type        []*PokemonType    `json:"type" gorm:"many2many:pkmn_types;"`
	Abilities   []*PokemonAbility `json:"abilities" gorm:"many2many:pkmn_abilities;"`
}

type PokemonAbility struct {
	ID   int    `json:"id" gorm:"primaryKey"`
	Name string `json:"name"`
}

type PokemonAbilityInput struct {
	Name string `json:"name"`
}

type PokemonInput struct {
	ID          *int                   `json:"id,omitempty"`
	Name        string                 `json:"name"`
	Description string                 `json:"description"`
	Category    string                 `json:"category"`
	Type        []*PokemonTypeInput    `json:"type"`
	Abilities   []*PokemonAbilityInput `json:"abilities"`
}

type PokemonType struct {
	ID   int    `json:"id" gorm:"primaryKey"`
	Name string `json:"name"`
}

type PokemonTypeInput struct {
	Name string `json:"name"`
}
